rm -rf ~/.vim/bundle
mkdir ~/.vim/bundle
cd ~/.vim/bundle
git clone https://github.com/mileszs/ack.vim.git
git clone https://github.com/rking/ag.vim
git clone https://github.com/ctrlpvim/ctrlp.vim.git
git clone https://github.com/dyng/ctrlsf.vim
git clone https://github.com/Shougo/deoplete.nvim.git
git clone https://github.com/junegunn/fzf
git clone https://github.com/itchyny/lightline.vim
git clone https://github.com/yegappan/mru.git
git clone https://github.com/scrooloose/nerdcommenter
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/tmhedberg/simpylfold
git clone https://tpope.io/vim/surround.git
git clone https://github.com/vim-syntastic/syntastic.git
git clone https://github.com/kchmck/vim-coffee-script
git clone https://github.com/altercation/vim-colors-solarized
git clone https://github.com/easymotion/vim-easymotion
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/roxma/vim-hug-neovim-rpc.git
git clone https://github.com/pangloss/vim-javascript
git clone https://github.com/elzr/vim-json
git clone https://github.com/plasticboy/vim-markdown
git clone https://github.com/terryma/vim-multiple-cursors.git
git clone https://github.com/tpope/vim-surround
git clone https://github.com/christoomey/vim-tmux-navigator
git clone https://github.com/maxbrunsfeld/vim-yankstack.git
git clone https://github.com/sjbach/lusty
git clone https://github.com/vim-scripts/LustyJuggler